100-hours-a-week/3-team-modie-be

- Dockerfile
- src/main/java/org/ktb/modie/TestEditorConfig.java
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> Feature: Add Dockerfile

- src/main/java/org/ktb/modie/domain/Meet.java
모임 엔티티 생성
Feature #11 
- Resolves #[11]
1. [Meet Entity 생성]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> feat: create meet entity

- src/main/java/org/ktb/modie/config/SwaggerConfig.java
- src/main/java/org/ktb/modie/presentation/v1/controller/HealthCheckApi.java
헬스 체크 경로 업데이트 (/api/v1/health -> /health)
- Resolves #[31]
1. 헬스체크 경로 업데이트
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix: update health check path

- src/main/java/org/ktb/modie/domain/Meet.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
- src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetRequest.java
- src/main/java/org/ktb/modie/presentation/v1/dto/MeetDto.java
- src/main/java/org/ktb/modie/presentation/v1/dto/UserDto.java
- src/main/java/org/ktb/modie/repository/UserMeetRepository.java
- src/main/java/org/ktb/modie/repository/UserRepository.java
- src/main/java/org/ktb/modie/service/MeetService.java
모임 상세조회 API 구현
- Resolves #[26]
1. 모임 상세 조회 기능 구현
2. 예외처리) 유효하지 않은 숫자
3. 예외처리) 존재하지 않는 모임
1. [테스트 1]
2. [테스트 2]
4. [테스트 3]
참여중인 멤버 리스트는 모임참여 기능이 미구현 상태이므로 빈 리스트를 넣어놨습니다!
> feat: get meet

- .github/workflows/cicd-prod.yml
- .github/workflows/cicd.yml
배포 자동화 파이프라인에 자동 롤백 기능을 추가하였습니다.
Auto Scaling Group(ASG) 롤링 배포 중 배포 실패 시 자동으로 이전 정상 버전(prod-stable)을 복구하도록 개선했습니다.
1. 기존 prod 이미지를 prod-stable로 백업하여 롤백 대비
2. 배포 진행 상태 체크 (describe-instance-refreshes) 추가
3. 배포 실패 시 자동 롤백
- ASG 롤링 배포 취소 (cancel-instance-refresh)
- 기존 정상 버전(prod-stable)을 prod 태그로 복구
4. 배포 성공 여부를 GitHub Actions에서 감지하여 실패 시 즉시 종료 (exit 1)
5. GitHub Actions 로그 가독성 개선 (에러 메시지 명확화, echo 추가)
1. 배포 정상 진행 테스트
- 새로운 prod 이미지를 배포 후 ASG 롤링 업데이트 정상 수행 확인
2. 배포 실패 시 자동 롤백 테스트
- 잘못된 prod 이미지를 배포 후 ASG 상태 확인 (describe-instance-refreshes)
- 실패 감지 후 prod-stable로 자동 롤백 확인
3. GitHub Actions 성공/실패 상태 확인
- 정상 배포 시 성공 로그 출력
- 배포 실패 시 롤백 후 Actions 종료 (exit 1)
이번 개선을 통해 배포 실패 시 빠르게 롤백할 수 있어 안정성이 향상됨
추가적으로, 배포 실패 원인 분석을 위한 로그 출력 기능을 더 보강할 예정
> be-prod CICD 파이프라인 구축 및 자동 롤백 기능 추가

- src/main/java/org/ktb/modie/domain/Meet.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
- src/main/java/org/ktb/modie/repository/MeetRepository.java
- src/main/java/org/ktb/modie/service/MeetService.java
모임 삭제 API
- Resolves #[54]
1. 병합하면서 사라진 모임 삭제 API 복원
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
soft delete 구현
> fix: restore delete meet api

- src/main/java/org/ktb/modie/config/WebSocketConfig.java
cors 수정만 했습니다..
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix: cors 수정

- .github/workflows/cicd.yml
Docker 컨테이너 실행 시 환경 변수로 JWT 시크릿 키 및 카카오 API 키를 추가하도록 설정하였습니다.  
CI/CD 및 운영 환경에서 보다 유연하게 환경 변수를 관리할 수 있도록 개선하였습니다.
1. Docker 실행 시 `-e` 옵션을 통해 `JWT_SECRET`, `KAKAO_API_KEY` 환경 변수를 설정할 수 있도록 변경
2. 보안 강화를 위해 민감한 정보를 코드 저장소에서 직접 관리하지 않도록 개선
1. `docker run -e JWT_SECRET=your_jwt_secret -e KAKAO_API_KEY=your_kakao_key ...` 방식으로 실행하여 환경 변수 설정 확인
2. 컨테이너 내부에서 `echo $JWT_SECRET` 및 `echo $KAKAO_API_KEY` 명령어를 사용해 환경 변수 정상 반영 여부 확인
3. 기존 기능에 영향이 없는지 테스트 진행
> feat: Docker 실행 시 JWT 시크릿 키 & 카카오 API 키 환경 변수 추가

- build.gradle
- src/main/java/org/ktb/modie/config/WebConfig.java
- src/main/java/org/ktb/modie/core/interceptor/JwtAuthenticationFilter.java
- src/main/java/org/ktb/modie/presentation/v1/controller/AuthController.java
- src/main/java/org/ktb/modie/service/JwtService.java
- src/main/java/org/ktb/modie/service/UserService.java
- src/main/resources/application.yml
기존 Session 기반 카카오 로그인 기능을 JWT로 변경 (자동로그인을 위한 기능 구현)
1. CORS 설정 수정
2. JWT 관련 기능 구현
3. 로그인 세션 삭제
> feat: jwt 로그인 기능 구현

- .github/workflows/cicd.yml
> fix:  환경변수 추가

- src/main/java/org/ktb/modie/config/SwaggerConfig.java
swagger base url 수정 (localhost -> dev-api.modie.site)
1. swagger base url 수정 (localhost -> dev-api.modie.site)
> fix: SwaggerConfig.java

- src/main/java/org/ktb/modie/config/SwaggerConfig.java
- src/main/java/org/ktb/modie/config/WebConfig.java
- src/main/java/org/ktb/modie/core/interceptor/JwtAuthenticationFilter.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
- src/main/java/org/ktb/modie/repository/UserMeetRepository.java
- src/main/java/org/ktb/modie/service/JwtService.java
- src/main/java/org/ktb/modie/service/MeetService.java
모임 조회 역할 로직 추가 
스웨거 토큰 추가 
jwt 예외처리 세분화
- Resolves #[71]
1. 모임 조회 역할 로직 추가 
2. 스웨거 토큰 확인 추가 
3. jwt 예외처리 세분화
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix: get meet role, add swagger authorization, add jwt exception

- .github/workflows/cicd.yml
JWT 시크릿 값 환경변수에 추가
1. JWT 시크릿값을 환경변수로 추가하였습니다.
> feat: JWT 시크릿 값 환경변수에 추가

- src/main/java/org/ktb/modie/config/WebSocketConfig.java
- src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
- src/main/java/org/ktb/modie/presentation/v1/controller/ChatHistoryController.java
- src/main/java/org/ktb/modie/presentation/v1/dto/ChatDto.java
기존 프로젝트 구조와 채팅 DTO 구조 통일 및 국내 시간대로 통일
> fix: 기존 프로젝트 구조와 채팅 DTO 구조 통일 및 국내 시간대로 통일

- src/main/java/org/ktb/modie/presentation/v1/dto/MeetDto.java
- src/main/java/org/ktb/modie/service/MeetService.java
모임 조회시 수정시간, 삭제시간, 종료시간 필드 null값이어도 포함 
- Resolves #[80]
1. 모임 조회시 수정시간, 삭제시간, 종료시간 필드 null값이어도 포함
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix: meetdto add createdat updatedat deletedat

- src/main/java/org/ktb/modie/repository/MeetRepository.java
- src/main/java/org/ktb/modie/repository/UserMeetRepository.java
- src/main/java/org/ktb/modie/service/MeetService.java
모임 목록 조회 관련 예외 사항 처리
- close #89 
1. 삭제된 모임을 제외하고 조회되도록 예외 처리
2. 현재 유저 관련 모임( 생성 또는 참여한 모임 )만 조회되도록 수정
> Fix - 모임 목록 조회 관련 예외처리

- src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
- src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
- src/main/java/org/ktb/modie/core/handler/GlobalExceptionHandler.java
- src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetRequest.java
- src/main/java/org/ktb/modie/service/MeetService.java
- src/main/resources/application.yml
모임 생성 예외 사항 처리
- close #63 
- close #77 
1. meetAt - ISO format 안지키는 값이 body로 넘어올 때 예외처리
2. meetAt - 현재 시각보다 1년 이후인 값이 넘어올 때 예외처리
> Fix - 모임 생성 예외처리2

- src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
- src/main/java/org/ktb/modie/repository/MeetRepository.java
- src/main/java/org/ktb/modie/service/MeetService.java
사용자와 관련된 모임만 조회되도록 기능을 수정했습니다.
- close #89
1. 사용자 ID 기준으로 모임 필터링 로직 추가  
1. 로그인한 사용자 기준으로 모임 목록 조회  
2. 다른 사용자 계정으로 로그인하여 결과 비교  
3. 모임이 하나도 없는 사용자 테스트
> FIX - 모임목록조회 수정

- src/main/java/org/ktb/modie/config/SwaggerConfig.java
> fix : CLRF to LF

- src/main/java/org/ktb/modie/core/handler/GlobalExceptionHandler.java
> FIX - editorConfig format 통일

- src/main/java/org/ktb/modie/config/SwaggerConfig.java
Edit SwaggerConfig
localhost to dev
> FIX - edit SwaggerConfig

- src/main/java/org/ktb/modie/core/interceptor/JwtAuthenticationFilter.java
- src/main/java/org/ktb/modie/service/MeetService.java
- Resolves #[92]
1. 토큰 없이 모임 조회(userId = "")할 때 meetRole = "guest"
2. 모임 역할 판단하는 로직 함수화.
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix: empty user id sets guest and seperate get meet role method

- src/main/java/org/ktb/modie/repository/MeetRepository.java
모임 목록 조회 API - meetType이 '기타' 일 때 운동, 이동, 빨래 제외하고 나머지 오도록
close #98 
1. 위 사항 반영되도록 조회되도록 쿼리 수정
> FIX - findFilteredMeets Query at MeetRepository

- src/main/java/org/ktb/modie/domain/Meet.java
fix : import package for build
> fix : import package for build

- src/main/java/org/ktb/modie/repository/UserMeetRepository.java
- src/main/java/org/ktb/modie/service/MeetService.java
모임 참여했다가 나가도 해당 유저의 meetRule이 member로 오는 문제 해결
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix: meetrule 수정 완료

- src/main/java/org/ktb/modie/service/UserService.java
초기 가입 유저의 빈 문자열 계좌 수정 안되는 상황 발생 
- Resolves #[104]
1. 초기 유저 생성시 bankName과 accountNumber 빈문자열로 초기화
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix: update account with empty string

- src/main/java/org/ktb/modie/presentation/v1/dto/MeetSummaryDto.java
모임 목록조회 에서 addressDetail -> addressDescription 으로 변경
- Resolves #[108]
1. 모임 목록조회 에서 addressDetail -> addressDescription 으로 변경
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix: change getsummarydto field name

- src/main/java/org/ktb/modie/repository/MeetRepository.java
> fix : edit MeetRepository findFilteredMeets Query for Order #103

- src/main/java/org/ktb/modie/repository/MeetRepository.java
모임 목록 조회에서 '음식' 카테고리가 기타에 나오지 않도록 쿼리 수정
> FIX - 모임 목록 조회 쿼리 수정

- src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
채팅 관련 예외처리 추가
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> feat: chat-exception 추가

- src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
이미 종료된 모임에 메세지 전송 불가하도록 예외처리
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> feat: chat-exception 채팅작성 날짜가 이전이면 예외처리 추가

- src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
POST meets 상태번호 200고정에서 201로 수정
> fix: POST meets 상태번호 200고정에서 201로 수정

- src/main/resources/application.yml
Timezone 재지정
1. UTC -> AsiaSeul 변경
> feat: Timezone Asia/Seoul로 설정

- src/main/java/org/ktb/modie/core/interceptor/JwtAuthenticationFilter.java
> fix: 유효하지 않은 인증정보 전달 시 응답바디 추가

- src/main/java/org/ktb/modie/repository/UserMeetRepository.java
- src/main/java/org/ktb/modie/service/MeetService.java
- Resolves #[125]
1. 비용 발생 안한 모임 -> 비용 발생 수정 -> 비용 발생 안함으로 수정 : 모임 종료가 안되는 오류 발생
2. 모임 시작 전 나간 유저가 있는 모임 : 비용 정산여부가 갱신이 안되어 모임종료가 안되는 오류 발생
> fix: complete meet when modified total cost to zero

- .github/workflows/cicd.yml
기존 배포 스크립트에서 신규 컨테이너가 정상 기동되기 전에 Nginx 포트 스왑이 발생하여 잠깐의 다운타임이 발생할 수 있던 문제를 해결하기 위해, `/health` 엔드포인트를 이용한 헬스체크 로직을 추가하였습니다. 이를 통해 컨테이너가 완전히 기동된 것을 확인한 뒤 Nginx 설정을 적용하도록 수정하였습니다.
---
---
1. `/health` 엔드포인트를 통한 신규 컨테이너 상태 확인 로직 추가 (`curl` 사용)
2. 컨테이너가 정상적으로 응답하지 않을 경우 롤백 처리 추가
3. 기존 `COMMIT_HASH`가 없을 경우 ECR에서 최신 태그를 가져오는 로직 제거 (CI에서 이미 지정되므로 중복 제거)
---
(해당 사항 없음)
---
1. `/health` 응답이 정상일 때 Nginx가 올바르게 재시작되는지 확인
2. `/health` 응답이 실패할 경우 컨테이너가 종료되고 롤백되는지 확인
3. 실제 배포 후 서비스 무중단 상태 유지되는지 테스트
---
---
- 실제 컨테이너 기동 시간에 따라 `curl` 체크 간격 및 반복 횟수는 조정 가능합니다.
- 추후 무중단 배포 안정성을 높이기 위해 로드밸런서와의 연동 또는 Canary 방식도 고려할 수 있습니다.
> Feat/cicd - 다운타임 최소화 기능 추가

- .github/workflows/cicd.yml
운영 환경 배포 자동화를 위한 블루그린 배포 스크립트를 추가하였습니다.  
신규 컨테이너 기동 후 `/health` 체크 → Nginx 라우팅 전환 → 이전 컨테이너 종료 방식으로 무중단 배포를 구현하였습니다.
1. ECR에서 최신 Docker 이미지 태그(COMMIT_HASH) 조회 및 pull
2. Blue/Green 포트 기반 신규 컨테이너 기동 (`8080`/`8081`)
3. `/health` 응답이 200일 경우에만 Nginx 설정 반영 및 reload
4. `/health` 실패 시 롤백 처리 및 종료
5. 이전 컨테이너 graceful stop 및 제거
N/A – CLI 기반 배포 스크립트
1. 신규 이미지 배포 시 정상 기동 여부 확인
2. `/health` 체크 실패 시 롤백 동작 테스트
3. nginx reload 성공/실패 분기 정상 작동 여부 확인
- Nginx 라우팅은 `set $active_backend backend-blue|green;` 방식으로 처리됩니다.
- 추후 Slack 알림 또는 GitHub Actions 연동 예정입니다.
> feat: 헬스채크기반 롤백 기능 구현

- .gitignore
- build.gradle
- src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
- src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
- src/main/java/org/ktb/modie/domain/FcmToken.java
- src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
- src/main/java/org/ktb/modie/presentation/v1/controller/UserApi.java
- src/main/java/org/ktb/modie/presentation/v1/controller/UserController.java
- src/main/java/org/ktb/modie/presentation/v1/dto/FcmTokenRequest.java
- src/main/java/org/ktb/modie/repository/FcmTokenRepository.java
- src/main/java/org/ktb/modie/repository/UserMeetRepository.java
- src/main/java/org/ktb/modie/service/FcmService.java
- src/main/resources/application.yml
FCM(Firebase Cloud Messaging) 기능을 사용하여 채팅의 알림 기능을 구현
Resolves #118 
1. Fcm 의존성 추가
2. Fcm 알림 Request Dto 생성
3. Fcm Server 통신 테스트 코드 삭제
4. Fcm 관련 key 환경 변수로 전환
5. Fcm token 저장 기능 구현
6. 알림 기능 구현
> Feature - 채팅 FCM 알림 기능 추가

- build.gradle
- src/main/java/org/ktb/modie/core/interceptor/ApiThrottlingFilter.java
api-throttling 1초에 5번 요청 차단
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> feat: api-throttling 1초에 5번 요청 차단

- build.gradle
- src/main/java/org/ktb/modie/config/FirebaseProperties.java
- src/main/java/org/ktb/modie/core/exception/CustomErrorCode.java
- src/main/java/org/ktb/modie/core/exception/CustomErrorMessage.java
- src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
- src/main/java/org/ktb/modie/presentation/v1/controller/ChatHistoryController.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
- src/main/java/org/ktb/modie/presentation/v1/controller/UserApi.java
- src/main/java/org/ktb/modie/presentation/v1/controller/UserController.java
- src/main/java/org/ktb/modie/presentation/v1/dto/FcmTokenRequest.java
- src/main/java/org/ktb/modie/repository/ChatRepository.java
- src/main/java/org/ktb/modie/repository/FcmTokenRepository.java
- src/main/java/org/ktb/modie/service/FcmService.java
- src/main/resources/application.yml
Firebase key -> 환경 변수로 변경
Fixes #118
> Fix - chat alarm Firebase 환경 변수 처리

- build.gradle
- src/main/java/org/ktb/modie/core/util/HashIdUtil.java
- src/main/java/org/ktb/modie/presentation/v1/controller/ChatController.java
- src/main/java/org/ktb/modie/presentation/v1/controller/ChatHistoryController.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetApi.java
- src/main/java/org/ktb/modie/presentation/v1/controller/MeetController.java
- src/main/java/org/ktb/modie/presentation/v1/dto/CreateMeetResponse.java
- src/main/java/org/ktb/modie/presentation/v1/dto/MeetSummaryDto.java
- src/main/java/org/ktb/modie/service/MeetService.java
- src/main/resources/application.yml
모임 Id를 hashing 처리
Close #114 
1. [DTO 수정]CreateMeetResponse, MeetSummaryDto, MeetDto
2. [Service 수정] createMeet, getMeetList, getMeet, deleteMeet, deleteMeet, deleteUserMeet, createUserMeet, updateMeet, completeMeet, updatePayments updateTotalCost
3. [Controller 수정] 위와 동일
meetId에 대한 보안도 필요하다고 생각해서 Base64 말고 Hashing을 사용했어요
> Feature - 모임 ID 해싱 기능 추가

- src/main/java/org/ktb/modie/presentation/v1/dto/MeetDto.java
- src/main/java/org/ktb/modie/presentation/v1/dto/UpdateMeetRequest.java
- src/main/java/org/ktb/modie/service/MeetService.java
모임수정 시  totalCost 최소값 유효성 검증
Fixes #150 
1. Dto 및 Api 에서 유효성 검증
2. Service에 불필요한 검증 로직 삭제
> Fix - totalCost 최소값 유효성 검증

- .github/workflows/cicd.yml
로그 디렉토리 `/var/log/modie/dev` 생성 및 소유권 설정 스크립트를 추가했습니다.  
서버 구동 시 필요한 로그 저장 경로를 보장하고, 퍼미션 문제를 방지하기 위함입니다.
1. `/var/log/modie/dev` 경로가 없을 경우 생성하는 명령어 추가
2. 생성된 디렉토리의 소유자를 현재 사용자로 변경하는 명령어 추가
3. 재실행 시에도 문제없이 동작하도록 `mkdir -p` 사용
- 해당 사항 없음 (UI 변경 없음)
1. 로컬 및 서버 환경에서 스크립트 실행하여 디렉토리 정상 생성 및 권한 변경 확인
2. 디렉토리 존재 시에도 에러 없이 스크립트가 정상 종료되는지 확인
- 이후 prod 환경용 경로(`/var/log/modie/prod`) 생성 스크립트 추가가 필요할 수 있습니다.
- 스크립트 실행 시 별도 퍼미션 설정(`chmod`) 추가 여부는 추후 결정 예정입니다.
> feat: log저장폴더 생성 로직 추가 및 버전 명시

- src/main/resources/logback-dev.properties
- src/main/resources/logback-prod.properties
- Resolves #159 
1. logback-dev.properties, logback-prod.properties - /var/log/modie/{branch} 로 수정
> fix: unify log path
